### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**
issue #3

### CODE REVIEW

**Review by woutersl — COMMENTED** [review]
This looks good to me ; but I would like to exclude the commit `refactor: use std instead of tokio to handle fs` (74184832955dc31f08e4ce6f7a01f5b1fe3ccccd). Those functions need to be async to that the whole storage layer is async. That is why the `tokio` variants are used instead of the `std` ones.
The rest can be merge as-is.
Thank you for your contribution!

**Comment by MarcAntoine-Arnaud** [comment]
I have changed from tokio to std due to some empty files.
And about async, you may call sync methods in async methods. The only reason is maybe to have better performances (as it's describe here: https://ryhl.io/blog/async-what-is-blocking/)

I will rollback and re-check if everything is fine with tokio.

**Comment by MarcAntoine-Arnaud** [comment]
I have re-swap to tokio, just refactor the code as it works.

**Review by woutersl — APPROVED** [review]
LGTM, nice work, thanks!

**Pull request merged**
